config/routes.rb
Rails.application.routes.draw do
  resources :items do 
    collection do 
      put :generate
    end
  end
  resources :transfers
  resources :budgets
  resources :categories
  resources :accounts
  devise_for :users

  get 'administrators', to: 'administrators#index'
  get 'toggle_admin', to: 'administrators#toggle_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

 root to: 'accounts#index'
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  has_many :items
  accepts_nested_attributes_for :items 

  paginates_per 5
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: %i[ show edit update destroy ]
  load_and_authorize_resource
  # GET /budgets or /budgets.json
  def index
    @budgets = Budget.all
    @budgets = Budget.order(params[:by] + " " + params[:order]).page params[:page] if params[:sort] == "true"
    @budgets = Budget.order(:id).page params[:page]
  end

  # GET /budgets/1 or /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets or /budgets.json
  def create
    @budget = Budget.new(budget_params)
    respond_to do |format|
      if @budget.save
        
        if !params[:budget][:items].nil?
          params[:budget][:items].each do |f| 
            Item.where(["id = #{f}"]).first.update(budget_id: @budget.id)
          end
        end
        
        format.html { redirect_to budgets_path, notice: "Budget was successfully created." }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1 or /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        Item.where(["budget_id = #{params[:id]}"]).update_all(budget_id: nil)
        if !params[:budget][:items].nil?
          params[:budget][:items].each do |f| 
            Item.where(["id = #{f}"]).first.update(budget_id: params[:id])
          end
        end
        format.html { redirect_to budgets_path, notice: "Budget was successfully updated." }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1 or /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: "Budget was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def budget_params
      params.require(:budget).permit(:name, :from, :expires, :user_id, items: [:id])
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<div class='my-24 mx-96'>
<%= form_with(model: budget) do |form| %>
  <% if budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
        <% budget.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field text-xl">
      <%= form.label :name %>
      <%= form.text_field :name, class: "p-2 focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-7 pr-12 border-gray-300 rounded-md", placeholder: "Name" %>
    </div>

   <div class="field text-xl">
      <%= form.label :from %>
      <div class="flex justify-between p-2 focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-7 pr-12 border-gray-300 rounded-md">
      <%= form.date_select :from %>
      </div>
    </div>

  <div class="field text-xl">
      <%= form.label :expires %>
      <div class="flex justify-between p-2 focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-7 pr-12 border-gray-300 rounded-md">
      <%= form.date_select :expires %>
      </div>
    </div>

  <div class="field text-xl">
      <%= form.label :items %>
      <p class=" text-sm text-gray-700 "> Add Items to your new Bugdet, you can always come here later... :)</p>
      <div class="p-3 grid grid-cols-2">
      <% if !budget.id.nil?%>
        <% Item.where(["budget_id = #{budget.id}"]).each do |item| %>
        <div>
          <%= form.check_box(:items, { :multiple => true, checked: true }, item.id, nil) %>
          <%= item.name %>
        </div>
        <% end %>
      <% end %>
      <% Item.where(budget_id: nil).each do |item| %>
      <div>
        <%= form.check_box(:items, { :multiple => true }, item.id, nil) %>
        <%= item.name %>
      </div>
      <% end %>
      </div>
      
    </div>

  <div class="hidden">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <div class="flex w-full">
      <%= form.submit "Save Bugdet", :class=> "my-3 w-full flex justify-center py-2 px-4 border border-transparent text-xl font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"  %>
    </div>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<%= render 'form', budget: @budget %>

app/views/budgets/index.html.erb
<%= notice %>
<div class="flex flex-row ">
  <div class="flex flex-col w-full">
  <div class="-my-2 overflow-x-auto">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="mt-12 shadow-lg overflow-hidden border border-gray-200 sm:rounded-lg">
        <div class="text-center text-3xl my-3 font-semibold">Budgets</div>
        <div class='flex justify-around my-6 '>
      
          <div class="w-1/3">
            <%= link_to '<div >&#10010; Create New Budget</div>'.html_safe , new_budget_path, title: "Crete New Budget", :class=> "w-full flex justify-center py-2 px-4 border border-transparent font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"  %>
          </div>
          <div class="w-1/3">
            <%= link_to '<div >&#10010; Create New Item</div>'.html_safe , new_item_path, title: "Crete New Item", :class=> "w-full flex justify-center py-2 px-4 border border-transparent font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"  %>
          </div>
        </div>
        <p class="font-medium p-1 my-2 mx-96 rounded-lg bg-indigo-600 text-center text-white">To generate a Transfer, please select a Budget</p>
        <table class="min-w-full divide-y divide-gray-200 border-b border-gray-200">
          <thead class="bg-gray-50">
            <tr>
             <th class="px-6 py-3 text-left  font-medium text-gray-500 uppercase tracking-wider" ><%= link_to '<div>Name &#x2195; </div>'.html_safe, budgets_path(:sort => true, :by => "name", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
             <th class="px-6 py-3 text-left  font-medium text-gray-500 uppercase tracking-wider" ><%= link_to '<div>From &#x2195; </div>'.html_safe, budgets_path(:sort => true, :by => "from", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
             <th class="px-6 py-3 text-left  font-medium text-gray-500 uppercase tracking-wider" ><%= link_to '<div>Expires &#x2195; </div>'.html_safe, budgets_path(:sort => true, :by => "expires", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
              
              <th scope="col" class="px-6 py-3 text-left font-medium text-gray-500 uppercase tracking-wider">
                Nº Items
              </th>
              <th scope="col" class="px-6 py-3 text-left font-medium text-gray-500 uppercase tracking-wider">
                Actions
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200 ">
            <% @budgets.where("user_id = #{current_user.id}").each do |budget| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="ml-4">
                    <div class=" font-medium text-gray-900">
                      <%= budget.name %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="ml-4">
                    <div class=" font-medium text-gray-900">
                      <%= budget.from %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="ml-4">
                    <div class=" font-medium text-gray-900">
                      <%= budget.expires %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="ml-4">
                    <div class=" font-medium text-gray-900">
                      <%= budget.items.count %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap flex flex-row gap-3">
                <%= link_to '<div>&#x2630; </div>'.html_safe, budget, title: "Show Budget" %>
                <%= link_to '<div>&#x270E; </div>'.html_safe, edit_budget_path(budget), title: "Edit Budget" %>
                <%= link_to '<div>&#x2718;</div>'.html_safe, budget, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete Budget" %>
              </td>
              </tr>
            <% end %>
          </tbody>
        </table>
       <div class="flex justify-between m-3 mx-12 items-center"> 
          <div class=""><%= page_entries_info @budgets.where("user_id = #{current_user.id}") %></div>
          <%= paginate @budgets.where("user_id = #{current_user.id}")%>
        </div>
      </div>
    </div>
  </div>
</div>

</div>

app/views/budgets/new.html.erb
<%= render 'form', budget: @budget %>

app/views/budgets/show.html.erb
<%= render 'transfers/form', transfer: @transfer = Transfer.new, budget: @budget %>