config/routes.rb
Rails.application.routes.draw do
  resources :items do 
    collection do 
      put :generate
    end
  end
  resources :transfers
  resources :budgets
  resources :categories
  resources :accounts
  devise_for :users

  get 'administrators', to: 'administrators#index'
  get 'toggle_admin', to: 'administrators#toggle_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

 root to: 'accounts#index'
end

app/views/shared/_navbar.html.erb
<div>
  <nav class="bg-gray-800">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <div class="flex items-center">
          <div class="flex-shrink-0">
          <div class='text-2xl text-white'>Personal Finances</div>
            
          </div>
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline space-x-4">
              <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
              
               <%= link_to 'Accounts', accounts_path, :class => "ml-3 relative bg-gray-800 text-white px-3 py-2 rounded-md font-medium hover:bg-gray-900 focus:bg-gray-700"  %>
               <%= link_to 'Budgets', budgets_path, :class => "ml-3 relative bg-gray-800 text-white px-3 py-2 rounded-md font-medium hover:bg-gray-900 focus:bg-gray-700"  %>
               
               <%= select("post", "category_id", Category.where(category_id: nil).pluck(:name, :id), {:include_blank =>  'All Categories',:selected => params[:search]}, :onchange => 'window.location= `/categories?search=${document.getElementById("post_category_id").value}`', class: "ml-3 relative bg-gray-800 text-white px-3 py-2 rounded-md font-medium hover:bg-gray-900 focus:bg-gray-700") %>
               <% if user_signed_in? %>
                <% if current_user.admin?  %>
                  <%= link_to 'Admin Panel', administrators_path, :class => "ml-3 relative bg-gray-800 text-white px-3 py-2 rounded-md font-medium hover:bg-gray-900 focus:bg-gray-700" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="block">
            <div class="ml-4 flex items-center md:ml-6">
             <div class="text-white font-bold text-xl"><%= "#{current_user.last_name}, #{current_user.first_name}" %></div>
             <%= link_to "Log out", destroy_user_session_path, :method => :delete , :class => "ml-3 relative bg-gray-900 text-white px-3 py-2 rounded-md font-medium" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </nav> 
</div>