config/routes.rb
Rails.application.routes.draw do
  resources :items do 
    collection do 
      put :generate
    end
  end
  resources :transfers
  resources :budgets
  resources :categories
  resources :accounts
  devise_for :users

  get 'administrators', to: 'administrators#index'
  get 'toggle_admin', to: 'administrators#toggle_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

 root to: 'accounts#index'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategories, class_name: "Category"
  has_many :items
  belongs_to :category, class_name: "Category", optional: true

  paginates_per 3
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  load_and_authorize_resource
  # GET /categories or /categories.json
  def index
    @categories = Category.all
    @categories = Category.order(:id).page params[:page]
    @categories = @categories.where(["cast(id as text) LIKE :search OR cast(category_id as text) LIKE :search", :search => ("%" + params[:search] + "%")]) unless params[:search].blank?
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :category_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def parent(category)
    if(category.category_id.nil?)
      return 'text-xl font-black'
    else
      return 
    end
  end
end

app/views/categories/_form.html.erb
<div class='my-24 mx-96'>

<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field text-xl">
    <%= form.label :name %>
    <%= form.text_field :name, class: "p-2 focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-7 pr-12 border-gray-300 rounded-md", placeholder: "Name" %>
  </div>

  <div class="field text-xl">
      <%= form.label :category_id , "Select a Parent Category", class: "flex w-full"  %>
      <div class="flex justify-center p-2 focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-7 pr-12 border-gray-300 rounded-md">
      <%= form.collection_select :category_id, Category.where(category_id: nil), :id, :name, {  prompt: "None" } %>
      </div>
    </div>


  <div class="actions">
    <div class="flex w-full">
      <%= form.submit "Save Category", :class=> "my-3 w-full flex justify-center py-2 px-4 border border-transparent text-xl font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"  %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<div class="flex flex-row ">
  <div class="flex flex-col w-full">
  <div class="-my-2 overflow-x-auto">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="mt-12 shadow-lg overflow-hidden border border-gray-200 sm:rounded-lg">
        <div class="text-center text-3xl my-3 font-semibold">Categories</div>
        <div class='flex justify-around my-6 '>
          <%# <form class='flex w-1/2' method="GET" action="/accounts"> 
            <input name="search" class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 " placeholder='Type something to search...' />
            <button type="submit" class="mx-4 w-1/3 flex justify-center py-2 px-4 border border-transparent font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 "> Search </button>
          </form> %>
          <div class="w-1/3">
            <%= link_to '<div >&#10010; Create New Category</div>'.html_safe , new_category_path, title: "Crete New Category", :class=> "w-full flex justify-center py-2 px-4 border border-transparent font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"  %>
          </div>
          <div class="w-1/3">
            <%= link_to '<div >&#10010; Create New Item</div>'.html_safe , new_item_path, title: "Crete New Item", :class=> "w-full flex justify-center py-2 px-4 border border-transparent font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"  %>
          </div>
        </div>
        <table class="min-w-full divide-y divide-gray-200 border-b border-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider">
                ID
              </th>
              <th scope="col" class="px-6 py-3 text-left  font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left  font-medium text-gray-500 uppercase tracking-wider">
                Parent Category
              </th>
              <th scope="col" class="px-6 py-3 text-left font-medium text-gray-500 uppercase tracking-wider">
                Actions
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200 ">
            <% @categories.where(category_id: nil).each do |category| %>
            <tr class=" <%= parent(category) %> ">
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="ml-4">
                    <div class=" font-medium text-gray-900">
                      <%= category.id %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="ml-4">
                    <div class=" font-medium text-gray-900">
                      <%= category.name %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="ml-4">
                    <div class=" font-medium text-gray-900 text-center">
                      -
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap flex flex-row gap-3 text-base">
                <%= link_to '<div>&#x2630; </div>'.html_safe, category, title: "Show Account" %>
                <%= link_to '<div>&#x270E; </div>'.html_safe, edit_category_path(category), title: "Edit Account" %>
                <%= link_to '<div>&#x2718;</div>'.html_safe, category, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete Account" %>
              </td>
              </tr>
              
              <% category.subcategories.each do |cat| %>
              <tr >
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="ml-4">
                    <div class=" font-medium text-gray-900">
                      <%= cat.id %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="ml-4">
                    <div class=" font-medium text-gray-900">
                      <%= cat.name %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="ml-4">
                    <div class=" font-medium text-gray-900">
                      <%= category.name %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap flex flex-row gap-3">
                <%= link_to '<div>&#x2630; </div>'.html_safe, cat, title: "Show Account" %>
                <%= link_to '<div>&#x270E; </div>'.html_safe, edit_category_path(cat), title: "Edit Account" %>
                <%= link_to '<div>&#x2718;</div>'.html_safe, cat, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete Account" %>
              </td>
              </tr>
                        
            <% end %>
          <% end %>
          </tbody>
        </table>
        <div class="flex justify-between m-3 mx-12 items-center"> 
          <div class=""><%= page_entries_info @categories.where(category_id: nil) %></div>
          <%= paginate@categories.where(category_id: nil) %>
        </div>
      </div>
    </div>
  </div>
</div>

</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>


<div class="flex flex-row ">
  <div class="flex flex-col w-full">
  <div class="-my-2 overflow-x-auto">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="mt-12 shadow-lg overflow-hidden border border-gray-200 sm:rounded-lg">
        <div class="text-center text-3xl my-3 font-semibold"><%= @category.name %></div>
        <table class="min-w-full divide-y divide-gray-200 border-b border-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-md font-medium text-gray-500 uppercase tracking-wider">
                ID
              </th>
              <th scope="col" class="px-6 py-3 text-left  font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left  font-medium text-gray-500 uppercase tracking-wider">
                Description
              </th>
              <th scope="col" class="px-6 py-3 text-left font-medium text-gray-500 uppercase tracking-wider">
                Actions
              </th>
            </tr>
          </thead>
          <tbody>
          <% Item.where(["category_id = #{@category.id}"]).each do |i| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="ml-4">
                    <div class=" font-medium text-gray-900">
                        <%= i.id %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="ml-4">
                    <div class=" font-medium text-gray-900">
                      <%= i.name %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="ml-4">
                    <div class=" font-medium text-gray-900">
                      <%= i.description %>
                    </div>
                  </div>
                </div>
              </td>
               <td class="px-6 py-4 whitespace-nowrap flex flex-row gap-3">
                <%= link_to '<div>&#x2630; </div>'.html_safe, i, title: "Show Budget" %>
                <%= link_to '<div>&#x270E; </div>'.html_safe, edit_item_path(i), title: "Edit Budget" %>
                <%= link_to '<div>&#x2718;</div>'.html_safe, i, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete Budget" %>
              </td>
              </tr>

          <% end %>
          </tbody>
          </table>
          </div>
        </div>
    </div>
  </div>
</div>